- name: set host name
  ansible.builtin.shell: set-hostname frontend

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: placing expense config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: update nginx config
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: incluede app -prerequisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: starting nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

#- name: install filebeat
#  ansible.builtin.import_role:
#    name: elk
#    tasks_from: filebeat