- name: copy prometheus configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: copy prometheus config - record file
  ansible.builtin.template:
    src: record.yml
    dest: /opt/prometheus/record.yml

- name: copy prometheus config - alerts file
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
