- name: clean app content
  ansible.builtin.file:
    path: "{{app_loc}}"
    state: absent

- name: create new directory
  ansible.builtin.file:
    path: "{{app_loc}}"
    state: directory

- name: download  code and extract it
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: "{{app_loc}}"
    remote_src: yes