groups:
  - name: infra-alerts
    rules:
      - alert: ServerDownAlert
        expr: up==0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: server down alert

      - alert: FrontendServiceDownAlert
        expr: node_systemd_unit_state{exported_name="nginx.service",state="active"}==0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: frontend server down alert

      - alert: MysqlServiceDownAlert
        expr: node_systemd_unit_state{exported_name="mysqld.service",state="active"}==0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: mysql server down alert

      - alert: BackendServiceDownAlert
        expr: node_systemd_unit_state{exported_name="backend.service",state="active"}==0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: backend server down alert

      - alert: HighCpuUsage
        expr: 100-avg by(name)(rate(node_cpu_seconds_total{mode="idle"}[1m]))*100 > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: high cpu usage

      - alert: HighMemoryUsage
        expr: 100-((node_memory_MemFree_bytes+node_memory_Cached_bytes+node_memory_Buffers_bytes)/node_memory_MemTotal_bytes*100) > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: high memory usage